name: .NET

env:
  PROJECT_PATH: ' ./Example/Example.Test/Example.Test.csproj'

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore ${{env.PROJECT_PATH}}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{env.PROJECT_PATH}}
